"""uniq user username

Revision ID: 0b7ffc1d7e18
Revises: 5814cf8dcbcb
Create Date: 2025-05-25 23:26:10.315041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0b7ffc1d7e18'
down_revision: Union[str, None] = '5814cf8dcbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VehicleType')
    op.drop_table('PaymentMethod')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_user_username'))
        batch_op.create_index('uq_user_username', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('uq_user_username')
        batch_op.create_index(batch_op.f('idx_user_username'), ['username'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('PaymentMethod',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('icon', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VehicleType',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('icon', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###