"""roles-permissions2

Revision ID: 5814cf8dcbcb
Revises: 16e54d06f8f0
Create Date: 2025-05-25 05:51:12.934708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5814cf8dcbcb'
down_revision: Union[str, None] = '16e54d06f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VehicleType')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VehicleType',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('icon', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###