"""create initial tables

Revision ID: f8deab6bc998
Revises: 
Create Date: 2025-05-05 17:57:24.770586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #agregado manualmente 



# revision identifiers, used by Alembic.
revision: str = 'f8deab6bc998'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_created_by', 'Role', ['created_by'], unique=False)
    op.create_index('idx_role_name', 'Role', ['name'], unique=False)
    op.create_index('idx_role_updated_by', 'Role', ['updated_by'], unique=False)
    op.create_table('Toll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_toll_created_by', 'Toll', ['created_by'], unique=False)
    op.create_index('idx_toll_tax_id', 'Toll', ['tax_id'], unique=False)
    op.create_index('idx_toll_updated_by', 'Toll', ['updated_by'], unique=False)
    op.create_table('User',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('toll_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['toll_id'], ['Toll.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_by', 'User', ['created_by'], unique=False)
    op.create_index('idx_user_role_id', 'User', ['role_id'], unique=False)
    op.create_index('idx_user_toll_id', 'User', ['toll_id'], unique=False)
    op.create_index('idx_user_updated_by', 'User', ['updated_by'], unique=False)
    op.create_index('idx_user_username', 'User', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='User')
    op.drop_index('idx_user_updated_by', table_name='User')
    op.drop_index('idx_user_toll_id', table_name='User')
    op.drop_index('idx_user_role_id', table_name='User')
    op.drop_index('idx_user_created_by', table_name='User')
    op.drop_table('User')
    op.drop_index('idx_toll_updated_by', table_name='Toll')
    op.drop_index('idx_toll_tax_id', table_name='Toll')
    op.drop_index('idx_toll_created_by', table_name='Toll')
    op.drop_table('Toll')
    op.drop_index('idx_role_updated_by', table_name='Role')
    op.drop_index('idx_role_name', table_name='Role')
    op.drop_index('idx_role_created_by', table_name='Role')
    op.drop_table('Role')
    # ### end Alembic commands ###
